<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Module.aspx.cs" Inherits="Module" MasterPageFile="~/MasterPage.master"%>

<asp:Content ID="Content1" runat="server" 
    contentplaceholderid="ContentPlaceHolder1">
        <div  id="body" 
        
            style="border-color: #3D3A40; margin: auto; width:768px; border-right-style: solid; border-left-style: solid;">
    <br />
            <div class="style15">Create new Modules</div>
            
            <br />
            
        <fieldset>
        <legend style="padding: 3px; font-family: Rockwell; color: #FFFFFF; background-color: #808080; font-size: medium;">
            Enter new Module informations</legend>
               
        <table style="width:100%;">
            <tr>
                <td class="style16">
                    Code&nbsp;<asp:RegularExpressionValidator ID="RegularExpressionValidator1" 
                        runat="server" ControlToValidate="txtbxCode" ErrorMessage="*" 
                        ValidationExpression="\w{1,15}"></asp:RegularExpressionValidator></td>
                <td class="style16">
                    <asp:TextBox ID="txtbxCode" runat="server"></asp:TextBox>
                </td>
                <td rowspan="3" valign="top" 
                    style="text-align: center; font-family: 'Microsoft Sans Serif'; font-size: small">
                    Select the courses containing the new module (Optional)<br />
                    <asp:ListBox ID="lstbxCourses" runat="server" DataSourceID="CourseList" 
                        DataTextField="cname" DataValueField="ccode" Height="121px" 
                        SelectionMode="Multiple" style="font-family: 'Lucida Sans Unicode'; font-size: small" 
                        Width="352px" ToolTip="Select courses related (optional)"></asp:ListBox>
                    <asp:SqlDataSource ID="CourseList" runat="server" 
                        ConnectionString="<%$ ConnectionStrings:aptechConnectionString %>" 
                        
                        SelectCommand="SELECT [ccode], [cname] FROM [course_master] ORDER BY [cname]">
                    </asp:SqlDataSource>
                </td>
            </tr>
            <tr>
                <td class="style6">
                    Name
                    <asp:RegularExpressionValidator ID="RegularExpressionValidator2" runat="server" 
                        ControlToValidate="txtbxName" ErrorMessage="*" 
                        ValidationExpression="[\w- ]{10,100}"></asp:RegularExpressionValidator>
                </td>
                <td class="style2">
                    <asp:TextBox ID="txtbxName" runat="server" Width="290px"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="style6" valign="top">
                    Description
                    <asp:RegularExpressionValidator ID="RegularExpressionValidator3" runat="server" 
                        ControlToValidate="txtbxComment" ErrorMessage="*" ValidationExpression="{,200}"></asp:RegularExpressionValidator>
                </td>
                <td class="style2">
                    <asp:TextBox ID="txtbxComment" runat="server" Height="72px" 
                        style="font-family: Cambria" TextMode="MultiLine" Width="292px"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="style7" colspan="2">
                    <asp:Button ID="btnReset" runat="server" Text="Reset" Width="91px" />
                </td>
                <td align="right">
                    <asp:Button ID="btnCreate" runat="server" onclick="btnCreate_Click" 
                        Text="Create" Width="105px" />
                </td>
            </tr>
        </table>
        </fieldset>
        <br />
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
            AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="mcode" 
            DataSourceID="ModuleList" ForeColor="#333333" GridLines="None"           
             OnRowCommand="GridView1_RowCommand"
            style="text-align: center; font-family: 'Microsoft Sans Serif'; font-size: small;" 
            Width="100%" AllowSorting="True" 
                onselectedindexchanged="GridView1_SelectedIndexChanged">
            <RowStyle BackColor="#E3EAEB" />
            <Columns>
                <asp:BoundField DataField="mcode" HeaderText="Code" ReadOnly="True" 
                    SortExpression="mcode" />
                <asp:BoundField DataField="mname" HeaderText="Name" SortExpression="mname" />
                <asp:ButtonField ButtonType="Button" CommandName="editModule" 
                    Text="Courses - Books" />
            </Columns>
            <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
            <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <EditRowStyle BackColor="#7C6F57" />
            <AlternatingRowStyle BackColor="White" />
        </asp:GridView>
        <asp:SqlDataSource ID="ModuleList" runat="server" 
            ConnectionString="<%$ ConnectionStrings:aptechConnectionString %>" 
            SelectCommand="SELECT * FROM [module_master] ORDER BY [mname]" 
                DeleteCommand="DELETE FROM [module_master] WHERE [mcode] = @mcode" 
                InsertCommand="INSERT INTO [module_master] ([mcode], [mname], [comment]) VALUES (@mcode, @mname, @comment)" 
                UpdateCommand="UPDATE [module_master] SET [mname] = @mname, [comment] = @comment WHERE [mcode] = @mcode">
            <DeleteParameters>
                <asp:Parameter Name="mcode" Type="String" />
            </DeleteParameters>
            <UpdateParameters>
                <asp:Parameter Name="mname" Type="String" />
                <asp:Parameter Name="comment" Type="String" />
                <asp:Parameter Name="mcode" Type="String" />
            </UpdateParameters>
            <InsertParameters>
                <asp:Parameter Name="mcode" Type="String" />
                <asp:Parameter Name="mname" Type="String" />
                <asp:Parameter Name="comment" Type="String" />
            </InsertParameters>
            </asp:SqlDataSource>    
    </div>
    <style type="text/css">
        .style15
        {
            text-align: center;
            font-family: Georgia;
            font-size: xx-large;
            font-weight: bold;
            color: #49464B;
        }
    .style16
    {
        height: 24px;
    }
    </style>

</asp:Content>

